version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8080:80
    depends_on:
      - app
    container_name: project_nginx

  app:
    build:
      args:
        user: danila # your username on your machine, you can get it by running echo $USER
        uid: 1000 # your uid which you can get by running id -u
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    container_name: project_app

  db:
    image: mysql:8.0
    restart: always
    #volumes:
    #  - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: project
      MYSQL_ROOT_PASSWORD: secretor
    ports:
      - 3306:3306
    #command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: project_db

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   links:
  #     - db
  #   environment:
  #     PMA_HOST: db
  #     PMA_PORT: 3306
  #     PMA_ARBITRARY: 1
  #   ports:
  #     - 8081:80
  #   depends_on:
  #     - db
  #   container_name: project_pma

  # redis:
  #   image: "redis:alpine"
  #   depends_on:
  #     - db
  #   container_name: project_redis

